server:
  #tomcat端口
  port: 9160
spring:
  #指定应用的名称，可选，如果不指定则默认为项目名称
  application:
    name: GuoSend
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/GuoSend_dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123
  redis:
    host: 192.168.63.100
    port: 6379
    password: 123
    database: 0
  cache:
    redis:
      time-to-live: 1800000
      #过期时间 30分钟
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
guoSend:
  path: D:\
  #表示上传文件的时候，自定义一个上传的位置